### ISSUE TITLE
dist/fisheyegl.js returns empty object

### ISSUE THREAD

**Issue by ccpandhare** [jywarren/fisheyegl#17]
`./src/fisheyegl.js` can be required in Node,
but `./dist/fisheyegl.js` can't. I am not sure how to instruct browserify to make this work.

**Comment by ccpandhare** [comment]
I mean `./dist/fisheyegl.js` when required, returns an empty object.

**Comment by ccpandhare** [comment]
I am sorry, I seem to have missed this part while testing. I apologize for that having got past me.

**Comment by jywarren** [comment]
isn't the main source file specified in package.json?

On Wed, Jul 26, 2017 at 10:48 PM, Chinmay Pandhare <notifications@github.com

**Comment by ccpandhare** [comment]
package.json specifies the main file to be `./dist/fisheyegl.js`

**Comment by ccpandhare** [comment]
I think we should implement the same solution as we did in image-sequencer here too.

**Comment by jywarren** [comment]
+1!

**Comment by ccpandhare** [comment]
Opened PR #18 for the same
