### ISSUE TITLE
port over threejs

### ISSUE THREAD

**Issue by PerspectivesLab** [jywarren/fisheyegl#29]
hi there ! thx for this project,
anyway on how to implement this in threejs ? 
thx

**Comment by jywarren** [comment]
Hmm. In not that familiar w three.js but can it wrap basic webgl code? This is mostly a shader I think! You could try with the underlying code...

**Comment by jywarren** [comment]
Take a look, it may be simpler to use this underlying code! 

https://github.com/bluemir/fisheye-correction-webgl

**Comment by PerspectivesLab** [comment]
thank you @jywarren i will try that !
